config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get     'login'        => 'sessions#new',     as: 'login'
  post    'authenticate' => 'sessions#create',  as: 'authenticate'
  delete  'logout'       => 'sessions#destroy', as: 'logout'

  resources :books do
    member do
      post 'like'
      delete 'unlike/:like_id', action: :unlike, as: 'unlike'
    end

    resources :reviews, only: %i[create destroy] do
      member do
        post 'like'
        delete 'unlike/:like_id', action: :unlike, as: 'unlike'
      end
    end
  end

  get '/profile'      => 'users#show'
  get '/profile/edit' => 'users#edit'
  resources :users, only: %i[update create new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :reviews
  has_many :likes, as: :likeable

  validates :name, :author, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :reviewer, class_name: 'User', foreign_key: 'user_id'
  has_many :likes, as: :likeable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :first_name, :last_name, :username, :password, :password_confirmation, presence: true
  has_secure_password

  def full_name
    "#{first_name} #{last_name}"
  end

  def liked?(subject)
    like(subject).present?
  end

  def like(subject)
    liked ||= likes.find_by(likeable: subject)
    liked
  end

  def reviewed_books
    Book.includes(reviews: :reviewer).select do |b|
      b.reviews.find { |r| r.reviewer.id == self.id }
    end
  end

  def favorite_books
    Book.includes(:likes).select do |b|
      b.likes.find { |l| l.user_id == self.id }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user
  before_action :ensure_login

  protected

  def logged_in?
    session[:user_id].present?
  end

  def ensure_login
    redirect_to login_path unless logged_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, except: %i[index new create]

  def index
    @books = Book.includes(:owner, :reviews).all
  end

  def new
    @book = current_user.books.new
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to @book, notice: "You have added #{@book.name} your collection"
    else
      flash[:alert] = @book.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Successfully updated'
    else
      flash[:alert] = @book.errors.full_messages.to_sentence
      set_book
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: 'Book deleted'
  end

  def like
    @book.likes.create user: current_user
    respond_to do |format|
      format.html { redirect_to @book }
      format.js { render 'actions' }
    end
  end

  def unlike
    like = @book.likes.find params[:like_id]
    like.destroy
    respond_to do |format|
      format.html { redirect_to @book }
      format.js { render 'actions' }
    end
  end

  private

  def book_params
    params.require(:book)
          .permit(
            :name,
            :author
          )
  end

  def set_book
    @book = Book.includes(:owner, reviews: %i[likes reviewer]).find params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_likeable, only: [:create]
  before_action :set_like, only: [:destroy]

  def create
    current_user.likes.create(likeable: @likeable)
    redirect_to @likeable.book
  end

  def destroy
    @like.destroy
    redirect_to @like.likeable.book
  end

  private

  def set_likeable
    @likeable = if params.keys.include? 'review_id'
                  Review.find(params[:review_id])
                end
  end

  def set_like
    @like = Like.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_book
  before_action :set_review, only: %i[destroy like unlike]

  def create
    @review = @book.reviews.build(review_params.merge(reviewer: current_user))
    respond_to do |format|
      if @review.save
        format.html { redirect_to @book, notice: 'Your comment was saved' }
        format.js
      else
        format.html { redirect_to @book, alert: @book.errors.full_messages.to_sentence }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @book }
      format.js
    end
  end

  def like
    @review.likes.create user: current_user
    respond_to do |format|
      format.html { redirect_to @book }
      format.js { render 'review' }
    end
  end

  def unlike
    like = @review.likes.find(params[:like_id])
    like.destroy
    respond_to do |format|
      format.html { redirect_to @book }
      format.js { render 'review' }
    end
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def set_review
    @review = @book.reviews.find(params[:id])
  end

  def review_params
    params.require(:review)
          .permit(:comment)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_login, only: [:new, :create]

  def create
    user = User.find_by(username: params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'You are successfully logged in'
    else
      render 'new'
      flash[:alert] = 'Invalid username/password combination'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'You have been logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_login, only: [:new, :create]
  before_action :set_user, only: [:edit, :update]

  def new
    redirect_to profile_path if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to profile_path, notice: 'Account successfully created'
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def update
    if @user.update_attributes user_params
      redirect_to profile_path, notice: "Update successful"
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user)
          .permit(
            :first_name,
            :last_name,
            :username,
            :password,
            :password_confirmation
          )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_type(key)
    alert_hash = {
      'notice'  => 'success',
      'alert'   => 'danger'
    }
    alert_hash[key]
  end
end

app/helpers/book_likes_helper.rb
module BookLikesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_actions.html.erb
<% if current_user.liked?(book) %>
  <%= link_to 'Unlike', unlike_book_path(book, current_user.like(book)), method: :delete, remote: true, class: 'btn btn-outline-dark btn-sm' %>
<% else %>
  <%= link_to 'Like', like_book_path(book), method: :post, remote: true, class: 'btn btn-outline-dark btn-sm' %>
<% end %>

<% if current_user == book.owner %>
  <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-outline-primary btn-sm' %>
  <%= link_to 'Delete', book_path(book), method: :delete, class: 'btn btn-outline-danger btn-sm' %>
<% end %>

app/views/books/_book.html.erb
<%= content_tag :h3, book.name, class: 'text-primary' %>
<%= content_tag :p, book.author %>
<p class="font-weight-light">
  <small>
    Added by <%= book.owner.full_name %> |
    <%= pluralize(book.reviews.size, 'comment') %> |
    <%= pluralize(book.likes.size, 'like') %>
  </small>
 </p>

app/views/books/_book_form.html.erb
<div class="row mt-5 pt-3">
  <div class="col-md-6 offset-md-3">

  </div>
</div>
<%= form_for(@book) do |f| %>
  <div class="form-group">
    <%= f.label :name %> <br>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
  </div>

  <div class="form-group">
    <%= f.label :author %> <br>
    <%= f.text_field :author, class: 'form-control', placeholder: 'Author' %>
  </div>

  <%= f.submit class: 'btn btn-primary btn-block' %>
<% end %>

app/views/books/actions.js.erb
document.getElementById('book-details')
        .innerHTML = "<%= j(render @book) %>"
        
document.querySelector('.book-actions')
        .innerHTML = "<%= j(render 'actions', book: @book) %>"

app/views/books/edit.html.erb
<%= render 'book_form', book: @book %>

app/views/books/index.html.erb
<div class="list-group list-group-flush">
  <% @books.each do |book| %>
    <%= link_to render('book', { book: book }), book_path(book), class: 'list-group-item list-group-item-action' %>
  <% end %>
</div>

app/views/books/new.html.erb
<%= render 'book_form', book: @book %>

app/views/books/show.html.erb
<div id="book-details">
  <%= render @book %>
</div>

<div class="book-actions">
  <%= render 'actions', book: @book %>
</div>

<hr>

<h5 class="mt-5">Say something about this book</h5>
<%= form_for(:review, url: book_reviews_path(@book), remote: true) do |f| %>
  <%= f.text_area :comment, size: '25x5', class: 'form-control' %> <br>
  <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>

<br>
<hr>

<h5 class="mt-5">Other Reviews</h5>

<div id="reviews">
  <%= render @book.reviews %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container">
        <%= link_to 'Book Review', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to 'New Book', new_book_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Profile', profile_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login', login_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Join', new_user_path, class: 'nav-link' %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container pt-2 mt-5">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= alert_type(key) %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_review.html.erb
<div class="card mb-3" data-review-id=<%= review.id %>>
  <div class="card-header">
    <%= review.reviewer.full_name %>
  </div>

  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <%= simple_format review.comment, class: 'lead', style: 'font-size:1rem' %>
      <footer class="blockquote-footer"><em><%= time_ago_in_words review.created_at %> ago</em></footer>
    </blockquote>
  </div>

  <div class="card-footer">
    <% if current_user.liked?(review) %>
      <%= link_to pluralize(review.likes.size, 'Like'), unlike_book_review_path(review.book, review, current_user.like(review)), method: :delete, remote: true, class: 'btn btn-primary btn-sm' %>
    <% else %>
      <%= link_to pluralize(review.likes.size, 'Like'), like_book_review_path(review.book, review), method: :post, remote: true, class: 'btn btn-primary btn-sm' %>
    <% end %>

    <% if current_user == review.reviewer %>
      <%= link_to 'Delete', book_review_path(review.book, review), method: :delete, remote: true, class: 'btn btn-danger btn-sm' %>
    <% end %>
  </div>
</div>

app/views/reviews/create.js.erb
let review = document.createRange()
                     .createContextualFragment("<%= j(render @review) %>")

document.getElementById('reviews').appendChild(review)

document.querySelector("textarea#review_comment").value = ""

let bookDetailsDiv = document.getElementById('book-details')
bookDetailsDiv.innerHTML = "<%= j(render @book) %>"

app/views/reviews/destroy.js.erb
review = document.querySelector("[data-review-id='<%= @review.id %>']")
review.remove()

bookDetailsDiv = document.getElementById('book-details')
bookDetailsDiv.innerHTML = "<%= j(render @book) %>"

app/views/reviews/review.js.erb
document.querySelector("[data-review-id='<%= @review.id %>']")
  .innerHTML = "<%= j(render @review) %>"

app/views/users/_user_form.html.erb
<div class="row mt-3">
  <div class="col-md-6 offset-md-3">

    <%= form_for @user do |f|%>
      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, placeholder: 'First name', class: 'form-control' %>
        </div>

        <div class="form-group col-md-6">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, placeholder: 'Last name', class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, placeholder: 'username', class: 'form-control' %>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :password %>
          <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label 'Confirm Password' %>
          <%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'form-control' %>
        </div>
      </div>

      <p>
        <%= f.submit 'Sign Up', class: 'btn btn-primary btn-block'%>
      </p>
    <% end %>

  </div>
</div>

app/views/users/edit.html.erb
<%= render 'user_form' %>

app/views/users/new.html.erb
<%= render 'user_form' %>

app/views/users/show.html.erb
<div>
  <h3>Personal Info</h3>
  <p>
    First Name: <%= current_user.first_name %> <br/>
    Last Name: <%= current_user.last_name %> <br/>
    Username: <%= current_user.username %> <br/>
  </p>
  
  <%= link_to 'Edit', profile_edit_path %>
</div>

<div>
  <h3>Statistics</h3>
  <p>
    Total No. of Books Added: <%= current_user.books.size %> <br/>
    Total No. of Books Reviewed: <%= current_user.reviewed_books.size %> <br/>
    No. of Favourite Books: <%= current_user.favorite_books.size %> <br/>
  </p>
</div>

<div>
  <h3>My Books</h3>
  <%= render current_user.books %>
</div>

<div>
  <h3>Favorite Books</h3>
  <%= render current_user.favorite_books %>
</div>

<div>
  <h3>Reviewed Books</h3>
  <%= render current_user.reviewed_books %>
</div>